# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querybuilder_example', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestAuthor',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='TestBook',
            new_name='Book',
        ),
    ]
